FROM alpine:3.15

ADD entrypoint.sh /entrypoint.sh

RUN apk add --no-cache php7 php7-json php7-gmp bash hyperfine python3 py3-pip z3 z3-dev py3-z3 && \
    ln -sf /usr/bin/php7 /usr/bin/php && \
    chmod +x /entrypoint.sh && \
    chown -R nobody:nobody /entrypoint.sh

USER nobody

CMD /entrypoint.sh
VOLUME /code
