FROM alpine:3.16

ADD entrypoint.sh /entrypoint.sh

RUN apk add --no-cache php8 php8-gmp php8-opcache bash hyperfine python3 py3-pip z3 z3-dev py3-z3 && \
    ln -sf /usr/bin/php8 /usr/bin/php && \
    touch /etc/php8/conf.d/01_jit.ini && \
    chmod 777 /etc/php8/conf.d/01_jit.ini && \
    chmod +x /entrypoint.sh && \
    chown -R nobody:nobody /entrypoint.sh

USER nobody

CMD /entrypoint.sh
VOLUME /code
